version: '2'
services:
    server:
        build: .
        image: ehub_server:latest
        ports:
            - "8080:8080"
        mem_limit: 3G
        # Ubuntu doesn't have this supported by default
        # Run:
        #       docker info
        # to see if there is support
        # See this thread: https://github.com/moby/moby/issues/396
        memswap_limit: 1G
        # One core is: 100000
        cpu_quota: 600000
